import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Client from '../src/modules/clients/client.model.js';
import Project from '../src/modules/projects/project.model.js';
import User from '../src/modules/auth/auth.model.js';

dotenv.config();

const MASTER_DATA = {
  Panigrahna: [
    {
      client_id: 'RE-PG-2026-001',
      client_name: 'Rahul jeevani',
      project_number: 'Project 001',
      project_details: 'Wedding',
      location: 'banglore',
      duration: '4 days',
      team_photo: '4',
      team_video: '3',
      team_drone: '1',
      team_same_day_edit: '1',
      inward_photo: 'TRUE',
      inward_video: 'TRUE',
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'TRUE',
      outward_video_details: '10 Reels, 2 HL, 2 SF',
      outward_others: 'FALSE',
      outward_others_details: null,
    },
    {
      client_id: 'RE-PG-2026-002',
      client_name: 'Harsh Sayonee',
      project_number: 'Project 001',
      project_details: 'Prewedding',
      location: 'out of station',
      duration: '1 day',
      team_photo: '1',
      team_video: '1',
      team_drone: null,
      team_same_day_edit: null,
      inward_photo: 'TRUE',
      inward_video: 'TRUE',
      deliverables: null,
      outward_photo: 'TRUE',
      outward_photo_details: 'Prewedding Photos',
      outward_video: 'TRUE',
      outward_video_details: '1 Story, 1 prewedding',
      outward_others: 'FALSE',
      outward_others_details: null,
    },
    {
      client_id: 'RE-PG-2026-002',
      client_name: 'Harsh Sayonee',
      project_number: 'Project 002',
      project_details: 'Prewedding (Suwali Beach)',
      location: 'suwali beach',
      duration: '1 day',
      team_photo: null,
      team_video: '1',
      team_drone: null,
      team_same_day_edit: null,
      inward_photo: 'FALSE',
      inward_video: 'TRUE',
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'FALSE',
      outward_video_details: null,
      outward_others: 'FALSE',
      outward_others_details: null,
    },
    {
      client_id: 'RE-PG-2026-002',
      client_name: 'Harsh Sayonee',
      project_number: 'Project 003',
      project_details: 'Wedding',
      location: 'surat',
      duration: '3 days',
      team_photo: '3',
      team_video: '3',
      team_drone: '3',
      team_same_day_edit: '1',
      inward_photo: 'TRUE',
      inward_video: 'TRUE',
      deliverables: null,
      outward_photo: 'TRUE',
      outward_photo_details: 'Wedding Photos',
      outward_video: 'TRUE',
      outward_video_details: 'Same Day, SF',
      outward_others: 'FALSE',
      outward_others_details: null,
    },
    {
      client_id: 'RE-PG-2026-003',
      client_name: 'Ronak Jessica',
      project_number: 'project 001',
      project_details: 'Wedding',
      location: null,
      duration: '3 days',
      team_photo: '3',
      team_video: '4',
      team_drone: '1',
      team_same_day_edit: '1',
      inward_photo: 'TRUE',
      inward_video: 'TRUE',
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'TRUE',
      outward_video_details: 'Same day, SF Ronak, SF Jessica',
      outward_others: 'FALSE',
      outward_others_details: null,
    },
    {
      client_id: 'RE-PG-2026-004',
      client_name: 'Vinay Mansi',
      project_number: 'project 001',
      project_details: 'wedding',
      location: null,
      duration: '1 day',
      team_photo: '2',
      team_video: '2',
      team_drone: null,
      team_same_day_edit: null,
      inward_photo: 'TRUE',
      inward_video: 'TRUE',
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'TRUE',
      outward_video_details: 'HL, Pithi, SF',
      outward_others: 'TRUE',
      outward_others_details: 'album',
    },
    {
      client_id: 'RE-PG-2026-005',
      client_name: 'Krishna Rushiraj',
      project_number: 'project 001',
      project_details: 'Baby Shower',
      location: null,
      duration: '1 day',
      team_photo: '2',
      team_video: '2',
      team_drone: null,
      team_same_day_edit: null,
      inward_photo: 'TRUE',
      inward_video: 'TRUE',
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'TRUE',
      outward_video_details: 'Reel',
      outward_others: 'FALSE',
      outward_others_details: null,
    },
    {
      client_id: 'RE-PG-2026-006',
      client_name: 'Shiv Vaibhavi',
      project_number: 'project 001',
      project_details: 'kanku pagla',
      location: 'surat',
      duration: '1 day',
      team_photo: '1',
      team_video: '1',
      team_drone: null,
      team_same_day_edit: null,
      inward_photo: 'TRUE',
      inward_video: 'TRUE',
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'FALSE',
      outward_video_details: null,
      outward_others: 'FALSE',
      outward_others_details: null,
    },
    {
      client_id: 'RE-PG-2026-007',
      client_name: 'Vraj Pooja',
      project_number: 'project 001',
      project_details: 'wedding',
      location: null,
      duration: '3 days',
      team_photo: '3',
      team_video: '2',
      team_drone: '1',
      team_same_day_edit: '1',
      inward_photo: 'TRUE',
      inward_video: 'TRUE',
      deliverables: null,
      outward_photo: 'TRUE',
      outward_photo_details: 'Wedding Photos',
      outward_video: 'TRUE',
      outward_video_details: '2 reel, 2 HL, 1SF',
      outward_others: 'FALSE',
      outward_others_details: null,
    },
    {
      client_id: 'RE-PG-2026-008',
      client_name: 'Ayaan',
      project_number: 'project 001',
      project_details: 'janoi',
      location: null,
      duration: '2 days',
      team_photo: '2',
      team_video: '1',
      team_drone: '1',
      team_same_day_edit: null,
      inward_photo: 'TRUE',
      inward_video: 'TRUE',
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'TRUE',
      outward_video_details: '2HL, 1SF',
      outward_others: 'TRUE',
      outward_others_details: 'sign album',
    },
    {
      client_id: 'RE-PG-2026-009',
      client_name: 'Bhumit priyansha',
      project_number: 'project 001',
      project_details: 'wedding',
      location: null,
      duration: '4 days',
      team_photo: '2',
      team_video: '2',
      team_drone: null,
      team_same_day_edit: '?',
      inward_photo: 'TRUE',
      inward_video: 'TRUE',
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'TRUE',
      outward_video_details: 'HL, SF',
      outward_others: 'FALSE',
      outward_others_details: null,
    },
    {
      client_id: 'RE-PG-2026-010',
      client_name: 'Aditi Bhargav',
      project_number: 'project 001',
      project_details: 'wedding',
      location: 'valsad',
      duration: '3 days',
      team_photo: '4',
      team_video: '3',
      team_drone: '1',
      team_same_day_edit: '1',
      inward_photo: 'TRUE',
      inward_video: 'TRUE',
      deliverables: null,
      outward_photo: 'TRUE',
      outward_photo_details: 'Wedding Photos',
      outward_video: 'TRUE',
      outward_video_details: '1HL, 8 Sangeet, 2 SF',
      outward_others: 'FALSE',
      outward_others_details: null,
    },
    {
      client_id: 'RE-PG-2026-011',
      client_name: 'Raj Krishi',
      project_number: 'project 001',
      project_details: 'engagement',
      location: 'surat',
      duration: '1 day',
      team_photo: '2',
      team_video: '1',
      team_drone: null,
      team_same_day_edit: null,
      inward_photo: 'TRUE',
      inward_video: 'TRUE',
      deliverables: null,
      outward_photo: 'TRUE',
      outward_photo_details: 'Engagement Photos',
      outward_video: 'TRUE',
      outward_video_details: '1 HL 1Reel',
      outward_others: 'FALSE',
      outward_others_details: null,
    },
    {
      client_id: 'RE-PG-2026-012',
      client_name: 'Rutvik Aishwarya',
      project_number: 'project 001',
      project_details: 'wedding',
      location: 'nashik',
      duration: '3 days',
      team_photo: '3',
      team_video: '3',
      team_drone: '1',
      team_same_day_edit: '1',
      inward_photo: 'TRUE',
      inward_video: 'TRUE',
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'TRUE',
      outward_video_details: '1 HL, 1 SF, 2 Reels',
      outward_others: 'FALSE',
      outward_others_details: null,
    },
    {
      client_id: 'RE-PG-2026-013',
      client_name: 'Dhruvi Het',
      project_number: 'project 001',
      project_details: 'engagement',
      location: 'surat',
      duration: '1 day',
      team_photo: '2',
      team_video: '2',
      team_drone: null,
      team_same_day_edit: null,
      inward_photo: 'TRUE',
      inward_video: 'TRUE',
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'TRUE',
      outward_video_details: '1 HL',
      outward_others: 'FALSE',
      outward_others_details: null,
    },
    {
      client_id: 'RE-PG-2026-014',
      client_name: 'Ronak Ishita',
      project_number: 'project 001',
      project_details: 'kanku pagla',
      location: 'surat',
      duration: '1 day',
      team_photo: '1',
      team_video: '1',
      team_drone: null,
      team_same_day_edit: null,
      inward_photo: 'TRUE',
      inward_video: 'TRUE',
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'TRUE',
      outward_video_details: '1 HL',
      outward_others: 'FALSE',
      outward_others_details: null,
    },
    {
      client_id: 'RE-PG-2026-015',
      client_name: 'Prachi Preet',
      project_number: 'project 001',
      project_details: 'wedding',
      location: null,
      duration: '2 days',
      team_photo: '3',
      team_video: '4',
      team_drone: '0',
      team_same_day_edit: '1',
      inward_photo: 'TRUE',
      inward_video: 'TRUE',
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'TRUE',
      outward_video_details: '1 HL',
      outward_others: 'TRUE',
      outward_others_details: 'Prachi album',
    },
    {
      client_id: 'RE-PG-2026-018',
      client_name: 'SatishBhai Desai',
      project_number: 'project 1',
      project_details: 'Retirement',
      location: 'valsad',
      duration: '1 day',
      team_photo: '2',
      team_video: '2',
      team_drone: null,
      team_same_day_edit: null,
      inward_photo: 'TRUE',
      inward_video: 'TRUE',
      deliverables: null,
      outward_photo: 'TRUE',
      outward_photo_details: 'Retirement Photos',
      outward_video: 'FALSE',
      outward_video_details: null,
      outward_others: 'FALSE',
      outward_others_details: null,
    },
    {
      client_id: 'RE-PG-2026-019',
      client_name: 'Manav',
      project_number: 'project 1',
      project_details: 'save the date',
      location: 'out of station',
      duration: '1 day',
      team_photo: '1',
      team_video: '1',
      team_drone: null,
      team_same_day_edit: null,
      inward_photo: 'TRUE',
      inward_video: 'TRUE',
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'TRUE',
      outward_video_details: 'save the date video',
      outward_others: 'FALSE',
      outward_others_details: null,
    },
  ],

  Aghhori: [
    {
      client_id: 'RE-AG-2026-001',
      client_name: 'ambika niketan',
      project_number: 'project 001',
      project_details: 'Website',
      inward_photo: 'TRUE',
      inward_video: 'FALSE',
      assigned_to: 'mayur',
      deliverables: null,
      outward_photo: 'TRUE',
      outward_photo_details: 'All Seva Photos',
      outward_video: 'TRUE',
      outward_video_details: 'trust, Opto and physio,bharti maiya old video, school, temple',
      outward_others: 'TRUE',
      outward_others_details: 'Website',
      notes_links: null,
    },
    {
      client_id: 'RE-AG-2026-001',
      client_name: 'ambika niketan',
      project_number: 'project 002',
      project_details: 'Logo',
      inward_photo: 'FALSE',
      inward_video: 'FALSE',
      assigned_to: null,
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'FALSE',
      outward_video_details: null,
      outward_others: 'TRUE',
      outward_others_details: 'logo / amimation',
      notes_links: null,
    },
    {
      client_id: 'RE-AG-2026-002',
      client_name: 'pehchan',
      project_number: 'project 001',
      project_details: 'Reel',
      inward_photo: 'FALSE',
      inward_video: 'FALSE',
      assigned_to: null,
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'FALSE',
      outward_video_details: null,
      outward_others: 'FALSE',
      outward_others_details: null,
      notes_links: null,
    },
    {
      client_id: 'RE-AG-2026-002',
      client_name: 'pehchan',
      project_number: 'project 002',
      project_details: 'Reliance',
      inward_photo: 'FALSE',
      inward_video: 'FALSE',
      assigned_to: null,
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'FALSE',
      outward_video_details: null,
      outward_others: 'FALSE',
      outward_others_details: null,
      notes_links: null,
    },
    {
      client_id: 'RE-AG-2026-003',
      client_name: 'Money Care',
      project_number: 'project 001',
      project_details: 'Reel',
      inward_photo: 'FALSE',
      inward_video: 'FALSE',
      assigned_to: null,
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'FALSE',
      outward_video_details: null,
      outward_others: 'FALSE',
      outward_others_details: null,
      notes_links: null,
    },
    {
      client_id: 'RE-AG-2026-003',
      client_name: 'Money Care',
      project_number: 'project 002',
      project_details: 'Event',
      inward_photo: 'TRUE',
      inward_video: 'FALSE',
      assigned_to: null,
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'FALSE',
      outward_video_details: null,
      outward_others: 'FALSE',
      outward_others_details: null,
      notes_links: null,
    },
    {
      client_id: 'RE-AG-2026-003',
      client_name: 'Money Care',
      project_number: 'project 002',
      project_details: 'Card Design',
      inward_photo: 'FALSE',
      inward_video: 'FALSE',
      assigned_to: null,
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'FALSE',
      outward_video_details: null,
      outward_others: 'TRUE',
      outward_others_details: 'Thank you cards',
      notes_links: null,
    },
    {
      client_id: 'RE-AG-2026-004',
      client_name: 'Suvera',
      project_number: 'project 1',
      project_details: 'product shoot',
      inward_photo: 'TRUE',
      inward_video: 'FALSE',
      assigned_to: null,
      deliverables: null,
      outward_photo: 'TRUE',
      outward_photo_details: 'Product shoot photos',
      outward_video: 'FALSE',
      outward_video_details: null,
      outward_others: 'FALSE',
      outward_others_details: null,
      notes_links: null,
    },
    {
      client_id: 'RE-AG-2026-004',
      client_name: 'Suvera',
      project_number: 'project 2',
      project_details: 'instagram',
      inward_photo: 'FALSE',
      inward_video: 'FALSE',
      assigned_to: null,
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'FALSE',
      outward_video_details: null,
      outward_others: 'TRUE',
      outward_others_details: 'Instagram creatives',
      notes_links: null,
    },
    {
      client_id: 'RE-AG-2026-005',
      client_name: 'Diu & Daman',
      project_number: 'project 1',
      project_details: 'khelo india',
      inward_photo: 'TRUE',
      inward_video: 'FALSE',
      assigned_to: 'daman hdd',
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'TRUE',
      outward_video_details: '4 reels, 6, HL',
      outward_others: 'FALSE',
      outward_others_details: null,
      notes_links: null,
    },
    {
      client_id: 'RE-AG-2026-005',
      client_name: 'Diu & Daman',
      project_number: 'Project 2',
      project_details: 'bag',
      inward_photo: 'FALSE',
      inward_video: 'FALSE',
      assigned_to: null,
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'FALSE',
      outward_video_details: null,
      outward_others: 'FALSE',
      outward_others_details: null,
      notes_links: null,
    },
    {
      client_id: 'RE-AG-2026-005',
      client_name: 'Diu & Daman',
      project_number: 'project 3',
      project_details: 'album',
      inward_photo: 'FALSE',
      inward_video: 'FALSE',
      assigned_to: null,
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'FALSE',
      outward_video_details: null,
      outward_others: 'FALSE',
      outward_others_details: null,
      notes_links: null,
    },
    {
      client_id: 'RE-AG-2026-005',
      client_name: 'Diu & Daman',
      project_number: 'Project 4',
      project_details: 'envelope',
      inward_photo: 'FALSE',
      inward_video: 'FALSE',
      assigned_to: null,
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'FALSE',
      outward_video_details: null,
      outward_others: 'FALSE',
      outward_others_details: null,
      notes_links: null,
    },
    {
      client_id: 'RE-AG-2026-005',
      client_name: 'Diu & Daman',
      project_number: 'project 5',
      project_details: 'modi visit',
      inward_photo: 'TRUE',
      inward_video: 'TRUE',
      assigned_to: null,
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'TRUE',
      outward_video_details: 'cycle rally, visit Documentary',
      outward_others: 'FALSE',
      outward_others_details: null,
      notes_links: null,
    },
    {
      client_id: 'RE-AG-2026-005',
      client_name: 'Diu & Daman',
      project_number: 'project 6',
      project_details: 'modi visit album',
      inward_photo: 'FALSE',
      inward_video: 'FALSE',
      assigned_to: null,
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'FALSE',
      outward_video_details: null,
      outward_others: 'TRUE',
      outward_others_details: 'album',
      notes_links: null,
    },
    {
      client_id: 'RE-AG-2026-005',
      client_name: 'Diu & Daman',
      project_number: 'project 7',
      project_details: 'airport flag off',
      inward_photo: 'TRUE',
      inward_video: 'TRUE',
      assigned_to: null,
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'TRUE',
      outward_video_details: '8 speeches, 1 HL',
      outward_others: 'FALSE',
      outward_others_details: null,
      notes_links: null,
    },
    {
      client_id: 'RE-AG-2026-006',
      client_name: 'Delhi',
      project_number: 'project 1',
      project_details: 'CM Shri School',
      inward_photo: 'TRUE',
      inward_video: 'TRUE',
      assigned_to: null,
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'TRUE',
      outward_video_details: '1 Reel 1 HL',
      outward_others: 'FALSE',
      outward_others_details: null,
      notes_links: null,
    },
    {
      client_id: 'RE-AG-2026-006',
      client_name: 'Delhi',
      project_number: 'Project 2',
      project_details: 'Yashotsav',
      inward_photo: 'TRUE',
      inward_video: 'FALSE',
      assigned_to: 'Preet',
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'FALSE',
      outward_video_details: null,
      outward_others: 'TRUE',
      outward_others_details: 'Opening Album & Sports Pages',
      custom_deliverables: [
        {
          title: 'Opening Album',
          category: 'others',
          details: 'shot by nayan team',
          status: 'delivered',
          deliveredAt: new Date(),
        },
        {
          title: 'Sports Album Pages in Closing',
          category: 'others',
          details: 'album pages in closing',
          driveUrl: 'https://drive.google.com/drive/folders/1DIVJDcbGsrPpa-I4JbcJYL_Fb_7HIC0V',
          status: 'delivered',
          deliveredAt: new Date(),
        },
        {
          title: 'Sports Event Media Drive',
          category: 'others',
          details: 'Sports and closing event drive assets',
          driveUrl: 'https://drive.google.com/drive/folders/1xiYS63KyP2pvXTiZ-Tq4KB1bkf_cJTAe',
          status: 'delivered',
          deliveredAt: new Date(),
        },
        {
          title: 'Closing Album',
          category: 'others',
          details: 'Closing album - footage by Preet',
          status: 'delivered',
          deliveredAt: new Date(),
        },
      ],
      notes_links: null,
    },
    {
      client_id: 'RE-AG-2026-006',
      client_name: 'Delhi',
      project_number: 'project 3',
      project_details: 'Frame',
      inward_photo: 'FALSE',
      inward_video: 'FALSE',
      assigned_to: null,
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'FALSE',
      outward_video_details: null,
      outward_others: 'TRUE',
      outward_others_details: '1 frame',
      notes_links: '1 frame with viral sir',
    },
    {
      client_id: 'RE-AG-2026-006',
      client_name: 'Delhi',
      project_number: 'Project 4',
      project_details: 'album',
      inward_photo: 'FALSE',
      inward_video: 'FALSE',
      assigned_to: null,
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'FALSE',
      outward_video_details: null,
      outward_others: 'TRUE',
      outward_others_details: 'CM Shri school album',
      notes_links: null,
    },
    {
      client_id: 'RE-AG-2026-006',
      client_name: 'Delhi',
      project_number: 'project 5',
      project_details: 'Vidya vahini logo',
      inward_photo: 'FALSE',
      inward_video: 'FALSE',
      assigned_to: null,
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'FALSE',
      outward_video_details: null,
      outward_others: 'TRUE',
      outward_others_details: 'Logo',
      notes_links: null,
    },
    {
      client_id: 'RE-AG-2026-006',
      client_name: 'Delhi',
      project_number: 'Project 6',
      project_details: 'Yoga Day',
      inward_photo: 'TRUE',
      inward_video: 'TRUE',
      assigned_to: null,
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'TRUE',
      outward_video_details: '1 HL',
      outward_others: 'FALSE',
      outward_others_details: null,
      notes_links: null,
    },
    {
      client_id: 'RE-AG-2026-007',
      client_name: 'Akta Wealth',
      project_number: 'Project 1',
      project_details: 'Backdrop',
      inward_photo: 'FALSE',
      inward_video: 'FALSE',
      assigned_to: null,
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'FALSE',
      outward_video_details: null,
      outward_others: 'TRUE',
      outward_others_details: 'backdrop design',
      notes_links: null,
    },
    {
      client_id: 'RE-AG-2026-007',
      client_name: 'Akta Wealth',
      project_number: 'project 2',
      project_details: 'talk show',
      inward_photo: 'FALSE',
      inward_video: 'TRUE',
      assigned_to: 'mayur 5 cam output',
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'TRUE',
      outward_video_details: 'mixer output',
      outward_others: 'FALSE',
      outward_others_details: null,
      notes_links: null,
    },
    {
      client_id: 'RE-AG-2026-008',
      client_name: 'Aurenza',
      project_number: 'Project 1',
      project_details: 'Logo',
      inward_photo: 'FALSE',
      inward_video: 'FALSE',
      assigned_to: null,
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'FALSE',
      outward_video_details: null,
      outward_others: 'TRUE',
      outward_others_details: 'logo',
      notes_links: null,
    },
    {
      client_id: 'RE-AG-2026-008',
      client_name: 'Aurenza',
      project_number: 'Project 2',
      project_details: 'Visiting Card',
      inward_photo: 'FALSE',
      inward_video: 'FALSE',
      assigned_to: null,
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'FALSE',
      outward_video_details: null,
      outward_others: 'TRUE',
      outward_others_details: 'VC',
      notes_links: null,
    },
    {
      client_id: 'RE-AG-2026-009',
      client_name: 'Pause Cafe',
      project_number: 'Project 1',
      project_details: 'Logo',
      inward_photo: 'FALSE',
      inward_video: 'FALSE',
      assigned_to: null,
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'FALSE',
      outward_video_details: null,
      outward_others: 'TRUE',
      outward_others_details: 'Logo',
      notes_links: null,
    },
    {
      client_id: 'RE-AG-2026-009',
      client_name: 'Pause Cafe',
      project_number: 'Project 2',
      project_details: 'Menu',
      inward_photo: 'FALSE',
      inward_video: 'FALSE',
      assigned_to: null,
      deliverables: null,
      outward_photo: 'FALSE',
      outward_photo_details: null,
      outward_video: 'FALSE',
      outward_video_details: null,
      outward_others: 'TRUE',
      outward_others_details: 'Menu',
      notes_links: null,
    },
  ],
};

function parseNum(val) {
  if (!val) return 0;
  const n = parseInt(String(val).trim(), 10);
  return isNaN(n) ? 0 : n;
}

async function run() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    // Reset all existing projects
    const deleteResult = await Project.deleteMany({});
    console.log(`Deleted ${deleteResult.deletedCount} existing projects.`);

    const adminUser = (await User.findOne({ role: 'super_admin' })) || (await User.findOne({}));
    if (!adminUser) {
      console.error('No admin user found!');
      process.exit(1);
    }
    console.log(`Using admin: ${adminUser.name} (${adminUser._id})`);

    let pgCount = 0;
    let agCount = 0;

    // 1. Process Panigrahna
    console.log('\n--- Importing Panigrahna Projects ---');
    for (const item of MASTER_DATA.Panigrahna) {
      if (!item.project_details) continue;

      const client = await Client.findOne({ clientId: item.client_id });
      if (!client) {
        console.warn(`[Panigrahna] Client not found: ${item.client_id} (${item.client_name})`);
        continue;
      }

      const photoIn = item.inward_photo === 'TRUE';
      const videoIn = item.inward_video === 'TRUE';

      const inwardData = {
        photo: photoIn,
        video: videoIn,
        source: item.assigned_to || '',
        storageLocation: '',
        status: photoIn || videoIn ? 'received' : 'pending',
        notes: item.location ? `Location: ${item.location}` : '',
        customFields: [],
      };

      const deliverables = [];
      if (item.outward_photo === 'TRUE') {
        deliverables.push({
          title: item.outward_photo_details || `${item.project_details} Photos`,
          category: 'photo',
          details: item.outward_photo_details || '',
          status: 'delivered',
          deliveredAt: new Date(),
        });
      }

      if (item.outward_video === 'TRUE') {
        deliverables.push({
          title: item.outward_video_details || `${item.project_details} Video`,
          category: 'video',
          details: item.outward_video_details || '',
          status: 'delivered',
          deliveredAt: new Date(),
        });
      }

      if (item.outward_others === 'TRUE') {
        deliverables.push({
          title: item.outward_others_details || `${item.project_details} Deliverable`,
          category: 'others',
          details: item.outward_others_details || '',
          status: 'delivered',
          deliveredAt: new Date(),
        });
      }

      if (deliverables.length === 0) {
        deliverables.push({
          title: item.project_details,
          category: 'others',
          details: 'Awaiting production',
          status: 'pending',
        });
      }

      const hasDelivered = deliverables.some((d) => d.status === 'delivered');
      const allDelivered = deliverables.every((d) => d.status === 'delivered');
      const projectStatus = allDelivered ? 'completed' : hasDelivered ? 'active' : 'planning';

      const teamDeployment = {
        counts: {
          photographers: parseNum(item.team_photo),
          videographers: parseNum(item.team_video),
          cinematographers: 0,
          dronePilots: parseNum(item.team_drone),
          sameDayEditors: parseNum(item.team_same_day_edit),
          editors: 0,
          others: 0,
        },
        crewMembers: [],
        customDetails: [],
      };

      await Project.create({
        projectCode: item.project_number || '',
        title: item.project_details,
        location: item.location || '',
        duration: item.duration || '',
        description: `${client.companyName} - ${item.project_details}${
          item.location ? ` | Location: ${item.location}` : ''
        }${item.duration ? ` | Duration: ${item.duration}` : ''}`,
        status: projectStatus,
        priority: 'medium',
        budget: 0,
        currency: 'INR',
        client: client._id,
        inwardData,
        deliverables,
        teamDeployment,
        createdBy: adminUser._id,
      });

      console.log(`  + [Panigrahna] [${item.client_id}] ${client.companyName} -> ${item.project_details}`);
      pgCount++;
    }

    // 2. Process Aghhori
    console.log('\n--- Importing Aghhori Projects ---');
    for (const item of MASTER_DATA.Aghhori) {
      if (!item.project_details) continue;

      const client = await Client.findOne({ clientId: item.client_id });
      if (!client) {
        console.warn(`[Aghhori] Client not found: ${item.client_id} (${item.client_name})`);
        continue;
      }

      const photoIn = item.inward_photo === 'TRUE';
      const videoIn = item.inward_video === 'TRUE';
      const source = item.assigned_to || '';

      const inwardData = {
        photo: photoIn,
        video: videoIn,
        source: source,
        storageLocation: '',
        status: photoIn || videoIn ? 'received' : 'pending',
        notes: source ? `Assigned / Source: ${source}` : '',
        customFields: [],
      };

      const deliverables = [];
      if (item.custom_deliverables && item.custom_deliverables.length > 0) {
        deliverables.push(...item.custom_deliverables);
      } else {
        if (item.outward_photo === 'TRUE') {
          deliverables.push({
            title: item.outward_photo_details || `${item.project_details} Photos`,
            category: 'photo',
            details: item.outward_photo_details || '',
            status: 'delivered',
            deliveredAt: new Date(),
          });
        }

        if (item.outward_video === 'TRUE') {
          deliverables.push({
            title: item.outward_video_details || `${item.project_details} Video`,
            category: 'video',
            details: item.outward_video_details || '',
            status: 'delivered',
            deliveredAt: new Date(),
          });
        }

        if (item.outward_others === 'TRUE') {
          const isUrl = item.notes_links && item.notes_links.startsWith('http');
          deliverables.push({
            title: item.outward_others_details || `${item.project_details} Deliverable`,
            category: 'others',
            details: item.outward_others_details || item.notes_links || '',
            driveUrl: isUrl ? item.notes_links : '',
            status: 'delivered',
            deliveredAt: new Date(),
          });
        }

        if (deliverables.length === 0) {
          deliverables.push({
            title: item.project_details,
            category: 'others',
            details: 'Awaiting production',
            status: 'pending',
          });
        }
      }

      const hasDelivered = deliverables.some((d) => d.status === 'delivered');
      const allDelivered = deliverables.every((d) => d.status === 'delivered');
      const projectStatus = allDelivered ? 'completed' : hasDelivered ? 'active' : 'planning';

      const teamDeployment = {
        counts: {
          photographers: photoIn ? 1 : 0,
          videographers: videoIn ? 1 : 0,
          cinematographers: 0,
          dronePilots: 0,
          sameDayEditors: 0,
          editors: 0,
          others: 0,
        },
        crewMembers: source ? [{ name: source, role: 'Lead Ingest / Shoot' }] : [],
        customDetails: [],
      };

      await Project.create({
        projectCode: item.project_number || '',
        title: item.project_details,
        description: `${client.companyName} - ${item.project_details}`,
        status: projectStatus,
        priority: 'medium',
        budget: 0,
        currency: 'INR',
        client: client._id,
        inwardData,
        deliverables,
        teamDeployment,
        createdBy: adminUser._id,
      });

      console.log(`  + [Aghhori] [${item.client_id}] ${client.companyName} -> ${item.project_details}`);
      agCount++;
    }

    console.log('\n=============================================');
    console.log(`Successfully imported both tabs!`);
    console.log(`Panigrahna Projects: ${pgCount}`);
    console.log(`Aghhori Projects:    ${agCount}`);
    console.log(`Total Projects:      ${pgCount + agCount}`);
    console.log('=============================================\n');

    process.exit(0);
  } catch (err) {
    console.error('Import error:', err);
    process.exit(1);
  }
}

run();
